# Generated by Django 6.0.5 on 2026-06-03 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_payment_card_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
